<!doctype html><html lang="id"><head><meta charset="utf-8"><style>
@page{margin:28px 34px}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#171717;font-size:9px}.header{border-bottom:3px solid #2455f5;padding-bottom:12px;margin-bottom:16px}.brand{font-size:22px;font-weight:bold;color:#2455f5}.brand span{color:#171717}.tagline{font-size:8px;letter-spacing:1px;color:#777}.period{float:right;text-align:right;margin-top:-34px}.period b{display:block;font-size:12px}.summary{width:100%;border-spacing:7px;margin:0 -7px 14px}.summary td{width:25%;padding:12px;border:1px solid #ddd}.summary small{display:block;font-size:7px;font-weight:bold;color:#666;margin-bottom:5px}.summary strong{font-size:13px}.income{color:#15803d}.expense{color:#b91c1c}.blue{color:#2455f5}h2{font-size:12px;margin:16px 0 7px}table.data{width:100%;border-collapse:collapse;margin-bottom:12px}table.data th{background:#2455f5;color:white;text-align:left;font-size:8px;padding:7px}table.data td{padding:7px;border-bottom:1px solid #ddd;vertical-align:top}table.data tr:nth-child(even) td{background:#f7f7f5}.right{text-align:right!important}.empty{text-align:center;color:#777;padding:14px!important}.total td{font-weight:bold;background:#f1f3ff!important;border-top:2px solid #2455f5}.category-grid{width:100%;border-spacing:12px 0;margin:0 -12px}.category-grid>tbody>tr>td{width:50%;vertical-align:top;padding-left:12px}.footer{position:fixed;bottom:-18px;left:0;right:0;color:#888;font-size:8px;border-top:1px solid #ddd;padding-top:5px}.pagenum:after{content:counter(page)}
</style></head><body>
<div class="header"><img src="{{ public_path('logo.png') }}" alt="NgeBadmintonYuk" style="width:145px;height:52px;object-fit:contain;object-position:left center"><div class="tagline">NGEBADMINTONYUK - MAIN BARENG, SEHAT &amp; SERU!</div><div class="period">Periode laporan<b>{{ \Carbon\Carbon::parse($start)->translatedFormat('d M Y') }} - {{ \Carbon\Carbon::parse($end)->translatedFormat('d M Y') }}</b></div></div>
<table class="summary"><tr><td><small>PEMASUKAN</small><strong class="income">{{ rupiah($totalIncome) }}</strong></td><td><small>PENGELUARAN</small><strong class="expense">{{ rupiah($totalExpense) }}</strong></td><td><small>SELISIH PERIODE</small><strong>{{ signed_rupiah($difference) }}</strong></td><td><small>SALDO AKHIR</small><strong class="blue">{{ rupiah($balance) }}</strong></td></tr></table>
<table class="category-grid"><tr><td><h2>Pemasukan per Kategori</h2><table class="data"><thead><tr><th>Kategori</th><th class="right">Total</th></tr></thead><tbody>@forelse($incomeByCategory as $name => $amount)<tr><td>{{ $name }}</td><td class="right">{{ rupiah($amount) }}</td></tr>@empty<tr><td colspan="2" class="empty">Tidak ada pemasukan</td></tr>@endforelse</tbody></table></td><td><h2>Pengeluaran per Kategori</h2><table class="data"><thead><tr><th>Kategori</th><th class="right">Total</th></tr></thead><tbody>@forelse($expenseByCategory as $name => $amount)<tr><td>{{ $name }}</td><td class="right">{{ rupiah($amount) }}</td></tr>@empty<tr><td colspan="2" class="empty">Tidak ada pengeluaran</td></tr>@endforelse</tbody></table></td></tr></table>
@foreach(['incomes' => 'Pemasukan', 'expenses' => 'Pengeluaran'] as $key => $label)
<h2>Daftar {{ $label }}</h2><table class="data"><thead><tr><th style="width:4%">No.</th><th style="width:12%">Tanggal</th><th style="width:16%">Kategori</th><th style="width:24%">Nama</th><th>Keterangan</th><th class="right" style="width:17%">Total</th></tr></thead><tbody>
@forelse($$key as $item)<tr><td>{{ $loop->iteration }}</td><td>{{ $item->date->translatedFormat('d M Y') }}</td><td>{{ $item->category->name }}</td><td>{{ $item->details->pluck('name')->join(', ') }}</td><td>{{ $item->description ?: '-' }}</td><td class="right">{{ rupiah($item->details_sum_amount) }}</td></tr>@empty<tr><td colspan="6" class="empty">Tidak ada transaksi {{ strtolower($label) }} pada periode ini.</td></tr>@endforelse
<tr class="total"><td colspan="5">TOTAL {{ strtoupper($label) }}</td><td class="right">{{ rupiah($key === 'incomes' ? $totalIncome : $totalExpense) }}</td></tr></tbody></table>
@endforeach
<div class="footer">NgeKas - NgeBadmintonYuk <span style="float:right">Halaman <span class="pagenum"></span></span></div></body></html>
